version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-hello-without-master:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello without master"
          command: "echo Hello, Hello without dev"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only: master
  say-nurba:
    jobs:
      - say-hello-without-master:
          filters:
            branches:
              ignore: master
