version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: nurba1713/cicleci-example
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:0.1.$CIRCLE_BUILD_NUM .
  publish-to-dockerhub:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME:$TAG .
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-to-dockerhub:
          context:
            - NURBEK_CONTEXT
          requires:
            - build
          filters:
            branches:
              only: master

















#version: 2.1
#
#jobs:
#  build-and-push-docker-image:
#    docker:
#      - image: cimg/go:1.17
#        auth:
#          username: nurba1713
#          password: nurba1713
#    steps:
#      - checkout
#      - setup_remote_docker:
#          version: 20.10.14
#          docker_layer_caching: true
#      - run: |
#          TAG=0.1.$CIRCLE_BUILD_NUM
#          cd circleci-example
#          docker build -t nurba1713/circleci:$TAG .
#          echo nurba1713 | docker login -u nurba1713 --password-stdin
#          docker push  nurba1713/circleci:$TAG
#
#  say-hello:
#    docker:
#      - image: cimg/base:stable
#    steps:
#      - checkout
#      - run:
#          name: "Say hello"
#          command: "echo Hello, World!"
##  say-hello-without-master:
##    docker:
##      - image: cimg/base:stable
##    steps:
##      - checkout
##      - run:
##          name: "Say hello without master"
##          command: "echo Hello, Hello without dev"
#workflows:
#  say-hello-workflow:
#    jobs:
#      - build-and-push-docker-image:
#          filters:
#            branches:
#              only: master
#      - say-hello
##  say-nurba:
##    jobs:
##      - say-hello-without-master:
##          filters:
##            branches:
##              ignore: master
